### ISSUE TITLE
"Exit RBTray" doesn't fully close the program.

### ISSUE THREAD

**Issue by WELZ-gh** [benbuck/rbtray#10]
I just right clicked on one of my minimized icons in the tray and selected <kbd>Exit RBTray</kbd>. Naturally, I thought that the program had closed, so I tested to confirm, and it had indeed closed.

I tried to launch the program again and got the message: "RBTray is already running"

So I tried minimizing a tab to tray and it **doesn't** work.

Did some digging... RBTray doesn't fully close when I hit <kbd>Exit RBTray</kbd> and just creates this endless loop of trying to open the program until you manually kill the task.

____
Steps to reproduce:

 - Start RBTray
 - Hide a window to tray
 - Right click that icon in tray and select <kbd>Exit RBTray</kbd>
 - Confirm it is closed by trying to minimize a window
 - Try reopening RBTray
 - Kill the task from taskmanager / cmd_
 - Repeat

**Comment by WELZ-gh** [comment]
Update: the new shortcut (Win+Alt+Down) still works even after *exiting*, but not the standard method.

**Comment by benbuck** [comment]
Version 4.8 should fix this.
