### ISSUE TITLE
Functionality Does not work in Windows 11

### ISSUE THREAD

**Issue by BroJenuel** [benbuck/rbtray#106]
Hi! So I started using this application but it seems that its not working on windows 11.

**Comment by latenightsurfer** [comment]
I can confirm @BroJenuel issue, does not run on my win 11, too

![image](https://github.com/benbuck/rbtray/assets/5868617/370015aa-55ee-4816-b9f7-4ca9117adbfb)

**Comment by oloasp** [comment]
Same here. Can't run neither 32 or 64bit version on Windows 11

**Comment by McflyBull** [comment]
You need to deactivate app control setting in security center.
