### ISSUE TITLE
Thank you for working on this program.

### ISSUE THREAD

**Issue by blubbll** [benbuck/rbtray#12]
It's not a minor fork, it's a brilliant one.

Thanks for those shortcuts.
Finally i can use RBTray in combination with
Opera (to listen to music in a background tab).

Thank you for keeping this project alive.

**Comment by benbuck** [comment]
Hi @blubbll,

Thanks so much for the positive feedback, I'm glad you are finding RBTray useful.

-Ben

**Comment by yzhang-gh** [comment]
Awesome! This is a great addition to Thunderbrid.
