### ISSUE TITLE
Mouse movement causes FPS drops in some 3D games while RBTray is running

### ISSUE THREAD

**Issue by Tembew** [benbuck/rbtray#13]
fps drops with mouse movement in some 3D games while the software is running. Specifically pathfinder kingmaker and dragon quest xi. Issue seen on a nvidia GPU, was not seen on an AMD GPU before. 

I was using 4t tray minimizer with an AMD gpu for months without issue. But with an upgrade to a 1080 the first game I ran showed some fps drops when the mouse was moved. I assumed it was just that game since some games did not have it. The game was dragon quest XI. It was not present in Rainbow Six siege and Shadow Tactics Blades of the showgun ( as far as I could tell). The issue popped up again in Pathfinder Kingmaker though. I shut down 4t and the issue was gone. So I started looking for alternatives, which brought me here. 

But, the issue is present with this software as well.

**Comment by benbuck** [comment]
@Tembew: I don't have these particular games, do they support both full-screen and window modes? If so, does the issue happen in both modes?

**Comment by Tembew** [comment]
it happened in both modes for pathfinder and dragon quest. I can recreate it in shadow tactics now as well with some combination of vsync on/off and fps cap removed. reproduced on 2d screens in phantom doctrine. I couldn't reproduce it in divinity original sin 2. 
I forgot I was seeing it in unigine heaven benchmark as well. extreme preset. there are fps drops when mousing over the benchmark window. You should be able to see the animation slow down. I use MSI afterburner to monitor my framerates.

**Comment by benbuck** [comment]
I just tested with Shadow Tactics and didn't notice any performance impact from moving the mouse.

**Comment by Tembew** [comment]
Yeah I didn't notice at first in that game. I had to set vsync to unlocked and it would drop from 150+ to 130+ with small repeated mouse movements. unigine heaven was more noticeable and its free to test.

**Comment by benbuck** [comment]
I still can't reproduce this. Do you want to try experimenting with the code to see if you can narrow down the issue?

**Comment by Tembew** [comment]
I am not familiar with the language. It seems a conflict with MSI afterburner. closing either fixes the issue. I will have to test whether reproducing it requires afterburner to be opened after opening the game.

**Comment by Tembew** [comment]
seems upgrading to rivatuner 7.2.0 fixed the issue for me. This is an app that runs when msi afterburner does and gives the in-game overlay. 

here is the changelog in case anything seems relevant
https://www.guru3d.com/files-details/rtss-rivatuner-statistics-server-download.html
