### ISSUE TITLE
Unable to Run Application on Windows 10

### ISSUE THREAD

**Issue by prestyman** [benbuck/rbtray#14]
RBTray appears to not work on Win10 system. Tried both 32 and 64 binaries with no success.  No problem with the original RBTray (2011 version)

![image](https://user-images.githubusercontent.com/6760197/47920871-6ced6200-de70-11e8-9fab-ab731ee15365.png)

System Details:
OS Name	Microsoft Windows 10 Home
Version	10.0.17134 Build 17134
System Manufacturer	Gigabyte Technology Co., Ltd.
System Type	x64-based PC
Processor	Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz, 3400 Mhz, 2 Core(s), 4 Logical Processor(s)

**Comment by benbuck** [comment]
Hi @prestyman,

This is strange, because probably most people that use this (including me) run on Windows 10. Could you please provide more information on your system? If you open the System Control Panel, what does it say under "System type"? Mine says "64-bit Operating System, x64-based processor", and I use the 64 bit version of RBTray.

Benbuck

**Comment by WELZ-gh** [comment]
@prestyman make sure you aren't using Windows 10 S (run `winver` to check)

**Comment by prestyman** [comment]
I was able to install the program and also duplicate the problem where I can't install.  If you download the binaries directly (just the RBHook.DLL and RBTray.exe) and try to install, it won't work.  This is only happens on a fresh install.  If I download the entire ZIP file, and then extract it, works fine.

does that help?

**Comment by prestyman** [comment]
File sizes seem substantially different. 
![image](https://user-images.githubusercontent.com/6760197/48149518-1f5a6600-e271-11e8-9dc6-f18e4cc50d29.png)

**Comment by bnason-nf** [comment]
I was able to directly download and run the x64 binaries without any issues, so I have to guess that whatever is causing this is happening on your end. Maybe you have something like anti-malware that is trying to protect you from downloading executables from the internet?

Benbuck

**Comment by benbuck** [comment]
I was able to directly download and run the x64 binaries without any issues, so I have to guess that whatever is causing this is happening on your end. Maybe you have something like anti-malware that is trying to protect you from downloading executables from the internet?

Benbuck

**Comment by benbuck** [comment]
I just noticed that the sizes of the binaries in the bad case (the smaller ones) are about the right size to be compressed files. Maybe somehow these are zip files that are named incorrectly? If you rename them to .zip and extract them, does that work?

Benbuck

**Comment by prestyman** [comment]
zip option didn't work, either.  I have no anti-malware running. You'll notice in the screen shot about, that the exe file icon looks different too.  Again, I have it running fine, but I just had to download the entire zip folder to do it.  Is it possible that something in the zip file is different?

**Comment by prestyman** [comment]
solved it. My ignorance with Github. I was right clicking and choosing "Save link as" rather than clicking the files and downloading from there. 
![image](https://user-images.githubusercontent.com/6760197/48152960-03a78d80-e27a-11e8-8e1e-e4519529e1be.png)

**Comment by WELZ-gh** [comment]
I'm guessing that the file size difference and the reason it didn't work has to do with your browser messing with the files (as a security precaution)

Try using a different browser to download it.

**Comment by jvaneck** [comment]
I had this same issue. Perhaps it would be better to save the release files in a zip or make a note in the readme not to 'save link as'

**Comment by benbuck** [comment]
Hi @jvaneck,

Thanks for the suggestion, I will look at this for the next release.

Benbuck

**Comment by benbuck** [comment]
Hi @jvaneck,

I added zip file artifacts to all of the versions on the [Releases page](https://github.com/benbuck/rbtray/releases) and updated the README.md to direct people to download from there. I think that should resolve this.

Thanks,
Benbuck
