### ISSUE TITLE
RBTray doesn't support Whatsapp APP

### ISSUE THREAD

**Issue by Ismael-GT** [benbuck/rbtray#16]
Thank you for still maintain RBTray, using it over 5 years..

I would like to inform a problem with WhatsApp application in windows 10.

The new key "Window+Alt+Down" works in WhatsApp app. but the right click in the WhatsApp application doesn't work.

I have always used this program in all these years because RBTray never support WhatsApp.

I had the strength to write this to finally stop using a specific program for WhatsApp to send to tray and in the future work only with RBTray <3
https://github.com/D4koon/WhatsappTray

Also, the fans are requesting it years ago; I have attached a picture showing a review from sourceforge
https://imgur.com/wOwRel1

Thanks I hope your answer!

**Comment by WELZ-gh** [comment]
The Right click key doesn't work in quite a few programs (issues with the programs functions etc.) which is why the Win+Alt+Down was created.

**Comment by benbuck** [comment]
@Ismael-GT: did @WELZ-gh's response help?

**Comment by Ismael-GT** [comment]
Yes, thanks!
