### ISSUE TITLE
Will not minimize an Oracle VirtualBox VM

### ISSUE THREAD

**Issue by bommerts** [benbuck/rbtray#18]
When trying to minimize a VM running from Oracle VirtualBox, the default "Restore, Move, Size..." etc dialog box pops up.

Works great on everything else I've tested.

**Comment by benbuck** [comment]
Hi @bommerts,

This seems like a duplicate of issue #4, have you tried using the Win+Alt+Down keyboard shortcut method to minimize VirtualBox?

Benbuck

**Comment by benbuck** [comment]
Hi @bommerts,

I'm closing this under the assumption that the keyboard shortcut will work for you, please let me know if not.

Benbuck
