### ISSUE TITLE
Opera browser minimizing problem

### ISSUE THREAD

**Issue by Alfoxxx** [benbuck/rbtray#21]
H! The best minimizing application have problem with minimizing the Opera web browser.
Opera window can not be minimized to the system tray by:
- Right-Clicking its minimize button
- Using the Windows-Alt-Down hotkey 
Works only:
- Shift-Right-Clicking on its title bar
Thanks!

**Comment by benbuck** [comment]
Hi @Alfoxxx,

Thanks for the feedback, I'm glad to hear RBTray works for your needs.

Benbuck

**Comment by vohahek531** [comment]
> * Using the Windows-Alt-Down hotkey
>   Works only:
> * Shift-Right-Clicking on its title bar

THANKS!

**Comment by benbuck** [comment]
Hi @vohahek531,

You're welcome, but now I'm wondering if I misunderstood you? Are you expecting all three methods of minimizing to work on every application? If so, unfortunately I don't know of any way to do that, some applications have non-standard window management that makes one ore more of the methods not work, and I don't plan to fix that.

Please let me know if I've missed something.

Thanks,
Benbuck
