### ISSUE TITLE
rbtray not working with msra win 10 190318362.30

### ISSUE THREAD

**Issue by rottweiller76** [benbuck/rbtray#25]
![error](https://user-images.githubusercontent.com/12532841/57285955-f9e1d400-70bc-11e9-836b-f0e824e75892.JPG)

hello, 

did not have any issues with rbtray till today, on previous windows versions all was ok :) , after the upgrade to win 10 190318362.30, the MSRA.exe tool is giving this error 

any ideas? (if i end task rbtray.exe, the tool starts correctly, if rbtray is active the error persists, and reappears after any ok pressed like in the image 

\rbtray\64bit\RBHook.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc0000428.

**Comment by benbuck** [comment]
Hi @rottweiller76,

I have not encountered this myself, so can't really guess what the problem is. Can you please explain how msra.exe is involved in running RBTray? Also, if you have any way to help identify or debug the problem, it would be appreciated.

Thanks,
Ben

**Comment by rottweiller76** [comment]
Hello, 

really no idea :)  but after you upgrade to W10 1903 just press start - run - MSRA.exe and see if you encounter same error

**Comment by benbuck** [comment]
Hi @rottweiller76, 

I just updated to Windows 10 build 1903, and can't reproduce this. Probably it's some other difference in our system configurations, but I don't have any clues about where to start looking. If you have any interesting possibilities, please share.

Thanks,
Benbuck

**Comment by benbuck** [comment]
Hi @rottweiller76,

Since I still can't reproduce this, and haven't heard anything from you in a year, I am going to close this. Please let me know if you have any new information to share.

Thanks,
Benbuck
