### ISSUE TITLE
Looks like 32/64 bit builds are in wrong location

### ISSUE THREAD

**Issue by Sangatster** [benbuck/rbtray#26]
When I first downloaded RBTray it was giving me issues so I did a little peeking at the bits and a PE header snooper app I use, TrID by M. Pontello is telling me the 32-bit files are in the 64-bit folder and 64-bit files in the 32-bit folder here :P

Could be wrong, but running the "32-bit" version resolved issues I was having and I'm running 64-bit Windows 10.  Trid is usually pretty accurate identifying PE signatures.

**32-bit files:**
Collecting data from file: C:\Util\Startups\RBTray\32Bit\RBTray.exe
 43.5% (.DLL) Win32 Dynamic Link Library (generic) (6578/25/2)
 29.8% (.EXE) Win32 Executable (generic) (4508/7/1)
 13.2% (.EXE) Generic Win/DOS Executable (2002/3)
 13.2% (.EXE) DOS Executable Generic (2000/1)

Collecting data from file: C:\Util\Startups\RBTray\32Bit\RBHook.dll
 64.6% (.EXE) Win64 Executable (generic) (27638/28/4)
 15.3% (.DLL) Win32 Dynamic Link Library (generic) (6578/25/2)
 10.5% (.EXE) Win32 Executable (generic) (4508/7/1)
  4.6% (.EXE) Generic Win/DOS Executable (2002/3)
  4.6% (.EXE) DOS Executable Generic (2000/1)

**64-bit files**
Collecting data from file: C:\Util\Startups\RBTray\64Bit\RBTray.exe
 50.0% (.EXE) Generic Win/DOS Executable (2002/3)
 49.9% (.EXE) DOS Executable Generic (2000/1)

Collecting data from file: C:\Util\Startups\RBTray\64Bit\RBHook.dll
 50.0% (.EXE) Generic Win/DOS Executable (2002/3)
 49.9% (.EXE) DOS Executable Generic (2000/1)

**Comment by Sangatster** [comment]
Sigh...or not.  Maybe the DLLs are crossed?  This app clearly identifies the 32-bit app as a 32-bit app:

W32i   APP ENU         4.7.0.0 shp rbtray.exe
        Language        0x0409 (English (United States))
        CharSet         0x04b0 Unicode
        OleSelfRegister Disabled
        FileDescription RBTray
        InternalName    RBTray
        OriginalFilenam RBTray.exe
        ProductName     RBTray
        ProductVersion  4.8.0.0
        FileVersion     4.8.0.0
        LegalCopyright  Copyright ⌐ 1998-2011 Nikolay Redko, J.D. Purcell, Benbuck Nason

Whatever the case, the files in the 32-bit directory work better for me on both 32 and 64-bit apps.  Maybe that's normal idk.

**Comment by benbuck** [comment]
Hi @Sangatster,

Maybe try downloading the binaries again? They look right to me (using dumpbin.exe instead of TrID):

```
c:\src\rbtray-tmp\x86
> dumpbin RBTray.exe /headers | grep "machine \("
grep: Unmatched ( or \(

c:\src\rbtray-tmp\x86
> dumpbin RBTray.exe /headers | grep "machine ("
             14C machine (x86)

c:\src\rbtray-tmp\x86
> dumpbin RBHook.dll /headers | grep "machine ("
             14C machine (x86)

c:\src\rbtray-tmp\x86
> cd ..\x64

c:\src\rbtray-tmp\x64
> dumpbin RBTray.exe /headers | grep "machine ("
            8664 machine (x64)

c:\src\rbtray-tmp\x64
> dumpbin RBHook.dll /headers | grep "machine ("
            8664 machine (x64)
```

I'm running the x64 version fine, and I think a number of other people are as well. Is there some issue you're encountering, or are you just curious about the binary format?

Thanks,
Benbuck

**Comment by Sangatster** [comment]
Mostly curious about the format. The ones marked as 32 bit worked better
for my machine for some reason so I peeked at it and thought maybe they
were flipped.

No big deal. Been using your build of RBTray since posted that and it's
working great!

**Comment by benbuck** [comment]
Thanks @Sangatster, I'm closing this out now.

-Benbuck
