### ISSUE TITLE
Can't interact with both admin and non-admin windows

### ISSUE THREAD

**Issue by ghost** [benbuck/rbtray#27]
Due to UAC, applications can only interact with other applications on the same access level.

When RBTray is ran as administrator, it can perform its functions on windows that have been ran as administrator, but no other windows.

Similarly, when RBTray is not ran as administrator, it can perform its functions on windows that are not running as administrator.

**Comment by benbuck** [comment]
Hi,

This seems related to this comment: https://github.com/benbuck/rbtray/issues/22#issuecomment-474712536, which then spawned issue #24, so I think this is a duplicate, and am going to close it. (Also for what it's worth the user who reported this has been deleted.)

Benbuck
