### ISSUE TITLE
Does not work on whatsapp desktop client

### ISSUE THREAD

**Issue by kofifus** [benbuck/rbtray#3]
Does not work on whatsapp desktop client :(

Maybe you can have a look ...

**Comment by benbuck** [comment]
Works for me, try using Shift+Middle-Mouse click on the title bar.

**Comment by kofifus** [comment]
No not working (win 64 creators) ..

Seem to not work on other 'universal windows app' as well (ie notion.so) ...

I found this https://github.com/D4koon/WhatsappTray which seems to be based on RBtray

**Comment by benbuck** [comment]
I'm using Win10 64 bit Creator's Edition also. Which version of rbtray are you using, 32 or 64 bit?

**Comment by kofifus** [comment]
I just removed and reinstalled the 64 bit version, the problem remains on whatsapp, notion.so and thunderbird

**Comment by benbuck** [comment]
That's unfortunate, thanks for trying though. I would really like to fix this, but I have no idea what might be wrong. It seems similar to the problem another user was having (see issue #2), though we never did figure out why.

What I see is that some apps (like WhatsApp and Visual Studio) seem to provide a non-standard minimize button, and the normal RBTray Right-Mouse click doesn't work on those. This is the main motivation for creating this fork of RBTray, which supports minimizing by using Shift+Right-Mouse click on the title bar also. Does this feature work for you on any other apps (e.g. Notepad), or just doesn't work at all?

Any information you can provide to help troubleshoot this would be appreciated.

Thanks,
Ben

**Comment by kofifus** [comment]
works sometimes ... checked with both right click on minize and right click on title bar:

total commander ok
visual studio 2017 - title bar only ok
foobar 2000 - ok
qbittorrent - no
notepad - no

some ideas:
- I didn't check but maybe this  https://github.com/D4koon/WhatsappTray can help ?
- perhaps inserting a 'minimize to tray' item to the context menu will work ?

**Comment by benbuck** [comment]
That's very strange that notepad wouldn't work. It works for me with both methods. There is clearly something different about our systems, but I don't know how to find out what it is. I'm wondering if maybe you are running some other piece of software that is also hooking mouse messages and maybe interfering with RBTray?

I looked at WhatsappTray, and unfortunately it's not helpful because it's only intended to work for that app (it hard codes the window name, close button pixel sizes, etc.).

I could try adding a context menu, but that sounds much more intrusive than the current methods so I'd rather not.

**Comment by benbuck** [comment]
@kofifus: Is this still an issue for you? Any new information that might help me figure out the problem?

**Comment by kofifus** [comment]
Hi
Yes this is still an issue for me so basically I can't us rbTray :(
I tried restarting and reinstalling but problem remains.
Let me know if there is a anyway I can help you debug this.
Thx!

**Comment by benbuck** [comment]
I finally managed to reproduce this on my machine, and I think it should be fixed now. Please try the latest build and let me know if it works for you also.

**Comment by kofifus** [comment]
sorry nothing seems to change, works on only very few programs here. Seems even worse than before, chrome does not respond as well now :(

**Comment by TheSimArchitect** [comment]
It also doesn't work for WhatsApp on Windows 11. 😟
