### ISSUE TITLE
Does not work with command prompt

### ISSUE THREAD

**Issue by ingbabic** [benbuck/rbtray#30]
It would be awesome if somehow command prompt minimizing to system tray will also work. This is invreasingly important as many of dev servers are actually working in command prompt

**Comment by benbuck** [comment]
Hi @ingbabic,

Would you mind explaining what you mean by this? I am able to minimize command prompt windows to the tray as expected with RBTray, by right-clicking on the minimize button or by shift-right-clicking on the title bar.

Thanks,
Benbuck

**Comment by ingbabic** [comment]
Hi @benbuck 
Well, it simply does not go to system tray by either of mentioned actions. My OS in Windows 10.

**Comment by ingbabic** [comment]
Now I found out one thing. Minimizing command prompt to tray does not work if command prompt is opened with elevated security (Run as administrator). I need to minimize to tray, exactly such command prompts. Command prompt opened normally are minimized to tray. Hope this help  you.

**Comment by ingbabic** [comment]
Now I see, it works, if you start RBTray as administrator as well. Thank you very much, this is very useful tool

**Comment by benbuck** [comment]
Hi @ingbabic,

I'm glad you figured this out. For the record, this seems related to https://github.com/benbuck/rbtray/issues/22#issuecomment-474712536, which spawned issue #24.

-Benbuck
