### ISSUE TITLE
Groove Music

### ISSUE THREAD

**Issue by prestyman** [benbuck/rbtray#35]
Unable to minimize Windows app Groove Music to tray. Icon goes to tray, my main app remains in taskbar. 
![2019-11-12 12_27_09-New Issue · benbuck_rbtray](https://user-images.githubusercontent.com/6760197/68708074-d0ac6f80-0547-11ea-9b5b-a179dcc818c4.png)

**Comment by benbuck** [comment]
Hi @prestyman,

This looks like the same issue as #22 (Groove Music is a Store app right?). Closing as duplicate.

Thanks,
Benbuck
