### ISSUE TITLE
Not working with VirtualBox

### ISSUE THREAD

**Issue by WELZ-gh** [benbuck/rbtray#4]
Doesn't work with VirtualBox

**Comment by benbuck** [comment]
I don't currently have VirtualBox installed, does it work if you hold Shift and Right-Click on the title bar instead of Right-Clicking on the minimize icon?

**Comment by WELZ-gh** [comment]
Nope, it works on the VirtualBox program, just not an actual Virtual Machine (which is what I wanted it for)

**Comment by benbuck** [comment]
Hi @WELZ-gh,

I just verified I'm seeing the same thing as you. I think my response to you in #6 applies here as well, so if you think of a solution that would work for these applications, please let me know.

Thanks,
Ben

**Comment by benbuck** [comment]
I was considering adding a global hotkey (maybe Win-Alt-Down) as an alternate method to minimize windows like these that are implemented in ways that are not compatibile with the Right-Click method. Would that work for you?

**Comment by WELZ-gh** [comment]
Version 4.7 update (Win+Alt+Down) fixes this problem. #6

**Comment by robozb** [comment]
Yes, Win+Alt+Down works at the main app, but not at a virtual machine window :(

**Comment by robozb** [comment]
Virtual Box version: 6.1.2
RBTray Version: 4.10

**Comment by semoog** [comment]
Can confirm, that keyboard shortcut does not minimize an active virtual machine window.

**Comment by Chealer** [comment]
@robozb, @semoog : I'm not sure what happened for VirtualBox (was it not fixed, or did it come back?), but I guess this is now tracked in ticket #75.
