### ISSUE TITLE
Minor: Thunderbird right click on minimize button not working

### ISSUE THREAD

**Issue by decoder247** [benbuck/rbtray#40]
Unable to minimize using the right click on minimize button method in Mozilla Thunderbird. However, pressing `win+alt+⬇` and pressing `shift+right click` on the program window works.

**Comment by benbuck** [comment]
Hi @decoder247,

Unfortunately there's nothing I can do about this, it's the way Thunderbird is written, but this is the reason why RBTray supports multiple methods of minimizing windows. Closing.

Thanks,
Benbuck

**Comment by McGerbick** [comment]
Hi!

There's actually a workaround if Thunderbird's default window layout is not that important to you:
1. Right-click into the toolbar and select _Customize_.
The _Customize Toolbar_ window pops up.
2. Enable _Show Title Bar_.
3. Click on _Done_.

Now you can minimize Thunderbird by right-clicking on the minimize button.

Greetz,
McGerbick

**Comment by decoder247** [comment]
Thank you @McGerbick! This works for me. It was a minor issue to begin with, but glad to see there's a workaround if you're used to the right-click on minimize method 🙂
