### ISSUE TITLE
Does not work with Webstorm 2020

### ISSUE THREAD

**Issue by GridTrekkor** [benbuck/rbtray#42]
Was working on 2019 and previous.  Win+Alt+Down puts a Webstorm icon in the systray, but does not minify the window.  The systray icon disappears on mouseover.

Version 2020 changed the titlebar of the Window; there is now an integrated menu and titlebar.

**Comment by benbuck** [comment]
HI @GridTrekkor,

I'm not familiar with this application, but it sounds it is doing some clever custom thing with the window that is not compatible with RBTray. If you want to play around with it to see if you can come up with a patch, I'd welcome a pull request.

Thanks,
Benbuck

**Comment by highfeed** [comment]
I have this problem. @benbuck I think you need to install this app and fix it. :)

**Comment by GridTrekkor** [comment]
It's working for me after restarting WS (or restarting Windows, can't remember which).  Shift+Right-Click is what I use.

**Comment by benbuck** [comment]
Hi @GridTrekkor and @highfeed,

Is this still an issue?

Thanks,
Benbuck

**Comment by GridTrekkor** [comment]
Not an issue at this time.  Will close.
