### ISSUE TITLE
Minimize to tray, from script

### ISSUE THREAD

**Issue by tscizzlebg** [benbuck/rbtray#43]
I've seen this feature suggested on Sourceforge, but no answers. And haven't seen it mentioned on Github so figured I would.

`start /min program.exe` runs a program in a shell minimized, but it'd be great to hide it even more by minimizing to tray, like RBTray does.

Could RBTray do this, or do you experts have any suggestions for how to do this without RBTray?

**Comment by benbuck** [comment]
Hi @tscizzlebg,

This looks like the same request as issue as #20, closing as duplicate.

Thanks,
Benbuck
