### ISSUE TITLE
Feature request: Start command minimized to system tray

### ISSUE THREAD

**Issue by Dave--G** [benbuck/rbtray#46]
I have a primitive little network monitoring script that currently runs minimized at startup.  I want to get it off the taskbar.  Rather than run as a hidden task scheduler job which deprives it of desktop UI notifications, I would like to simply be able to run 'rbtray X' where X is an arbitrary command line that I can specify (in this case run a batch file).  This would get the script out of the visible UI until an event triggers an alert.

I see a lot of requests for "start in tray" questions online so this new enhancement might be popular.

From a glance, all that seemingly needs to happen is a method to pass the command line arguments into an exec() call of some sort, grab the window handle created, then send that handle the minimize to tray windows message.

To me, ideally this behavior would take over the left-click minimize behavior of the window and would minimize it back to the notification area with no right-click required.

**Comment by benbuck** [comment]
Hi @Dave--G,

Agreed, this would be a nice feature. I think it's the same request as issue #20, so I'm closing it as Duplicate. Please let me know if you think it's different.

Thanks,
Benbuck

**Comment by Dave--G** [comment]
Thanks for the feedback, I missed that issue.  Is the feature actively being worked on or do you suggest I fork & do it myself?  I have Win32/64 API & windows message experience but not a lot of spare time...
