### ISSUE TITLE
Feature Request: Minimize Certain Apps Automatically

### ISSUE THREAD

**Issue by 1075dn** [benbuck/rbtray#47]
Hi Benbuck,
Is there any way to add a list (maybe from a config file) of apps that will automatically be hidden upon starting? Maybe also an option to have them automatically hide them instead of minimizing?
Thanks so much!

**Comment by benbuck** [comment]
Hi @1075dn,

There isn't currently any way to do this, and I agree that it would be nice to have. I think it's the same request as issue #20, so I'm closing it as Duplicate. Please let me know if you think it's different.

Thanks,
Benbuck
