### ISSUE TITLE
Disable hooking to certain applications

### ISSUE THREAD

**Issue by outpoints** [benbuck/rbtray#48]
While trying to play Halo MCC and having RBTray open it conflicts with EAC and stutters whenever you move the mouse.
Could you add a way to blacklist to certain applications?

Thanks!

**Comment by benbuck** [comment]
Hi @outpoints,

Have you tried running with the --no-hook option? It's not per-application as you requested, but maybe it's good enough?

-Benbuck

**Comment by benbuck** [comment]
Hi @outpoints,

Since it's not possible as far as I know to disable the hook feature per application, and since I haven't heard back from you, I'm going to close this out.

Thanks,
Benbuck

**Comment by Beridok** [comment]
Performance issues while playing Goose Goose Duck, which uses Easy Anti Cheat were observed by me.
Most suitable workaround would be to launch game as admin, while RBTray launches without admin. Then it does not hook to process. For that either game launcher (Steam, etc.) needs to be run as admin or separate game shortcut created.

**Comment by Beridok** [comment]
Performance issues while playing Goose Goose Duck, which uses Easy Anti Cheat were observed by me.
Most suitable workaround would be to launch game as admin, while RBTray launches without admin. Then it does not hook to process. For that either game launcher (Steam, etc.) needs to be run as admin or separate game shortcut created.

**Comment by MommyHeather** [comment]
I don't suppose this could be re-opened? I'm not knowledgable enough here, but I'd love it if this could be a feature. Right clicking the minimise button is by far the best method for me personally, but EAC games react violently to it - currently I resort to closing rbtray each time I wish to play one, but I'd rather not do that long-term.
