### ISSUE TITLE
Not working with Firefox 60 on Win10x64

### ISSUE THREAD

**Issue by metal450** [benbuck/rbtray#5]
Per the title :)

A few other reported it here, too: https://sourceforge.net/p/rbtray/activity/?page=0&limit=100#5a0316735fcbc91c3c7884f1

**Comment by benbuck** [comment]
This works fine for me if I hold Shift and Right-Click on the title bar, right clicking on the minimize icon doesn't work for Firefox and some other apps.

If that doesn't work for you, feel free to submit a patch.

**Comment by metal450** [comment]
Aha! You're right, shift-titlebar does work (I'd only known about doing it via the minimize button).  Cheers, closing :)
