### ISSUE TITLE
How to minimize to tray from cmdline?

### ISSUE THREAD

**Issue by clsven** [benbuck/rbtray#50]
Is there a way to start a program (with parameters) and minimized it immediately to SysTray by using RBtray?

if not: This feature should be added.
It should look like similar to

RBtray -minimize "D:\mytools\sometool123.exe -parm1 AAA -parm2 BBB"

Thank you
Claudia

**Comment by benbuck** [comment]
Hi Claudia,

Thanks for the request. I think this is the same as issue #20, so I am going to resolve it as a duplicate, but please let me know if you think otherwise.

Thanks,
Benbuck
