### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by PaulosKapa** [benbuck/rbtray#55]
would really like to have notifications pop up and make a sound (like when the app isnt on the tray), instead of just silently appearing on the notification panel.

**Comment by benbuck** [comment]
Hi @PaulosKapa,

Would you mind explaining this a bit more please? I don't think RBTray has any notifications. Maybe sharing a screen shot would help?

Thanks,
Benbuck

**Comment by PaulosKapa** [comment]
@benbuck 
after using rbtray for a bit i realised that it does what i asked for :).

**Comment by benbuck** [comment]
Hi @PaulosKapa,

I see, I'm going to close this then.

Thanks,
Benbuck
