### ISSUE TITLE
Does not work for FireFox or Thunderbird

### ISSUE THREAD

**Issue by tzr916** [benbuck/rbtray#57]
Works for Chrome.
Works for windows folders.

But won't work for FireFox or Thunderbird.

**Comment by benbuck** [comment]
Hi @tzr916,

For me it works on Firefox, but you have to use one of the alternate methods:

- Shift-Right-Clicking on its title bar
- Using the Windows-Alt-Down hotkey

Can you please try these to see if they work for you?

Thanks,
Benbuck

**Comment by tzr916** [comment]
Only Windows-ALT-Down is working for me.

**Comment by benbuck** [comment]
Hi @tzr916,

I'm glad to hear it's working. Please note that it's expected that not all of the methods work with every window type. Closing.

Thanks,
Benbuck
