### ISSUE TITLE
Doesn't work with Adobe Programs

### ISSUE THREAD

**Issue by WELZ-gh** [benbuck/rbtray#6]
Namely Photoshop and Illustrator, the problem sources from the fact that _Right clicking_ minimize in those programs performs the same action as _Left Click_.

**Comment by benbuck** [comment]
Hi @WELZ-gh,

Have you tried Shift+RightMouse clicking on the title bar instead of on the minimize button?

-Ben

**Comment by WELZ-gh** [comment]
@benbuck yep, nothing happens.

**Comment by benbuck** [comment]
Hi @WELZ-gh,

Sorry to hear that. Unfortunately it sounds like Adobe is doing some custom handling of mouse events within their window (including the minimize button and title bar), so I can't think of a good solution that would allow RBTray to work, can you?

Thanks,
Ben

**Comment by WELZ-gh** [comment]
Version 4.7update (Win+Alt+Down) fixes this problem.
