### ISSUE TITLE
System Icons disappear on minimize after Windows 10 21H1 update

### ISSUE THREAD

**Issue by bitx1** [benbuck/rbtray#61]
After Windows 21H1 update, my entire system tray area (i.e. icons, time, notifications) disappears after I minimize or restore an app from the system tray.

Couple Extra Notes
- I am running RBTray with elevated permissions.
- Restarting explorer.exe does not fix the problem (i.e. my system tray area still does not show after restart).
- To fix the problem without restarting; Taskbar settings -> temporarily update "Taskbar location on screen" setting to another location and then change it back
- I am running my desktop across 2 monitors. System tray area only appears on first monitor and time only appears on second monitor. The time on the second monitor is not impacted by use of RBTray.

UPDATE: it turns out that with RBTray running, ANY icon added or removed to the system (even by third-party apps), will make the system tray area disappear. For example, you can just open Window's Task Manager, which places an icon in the system tray, and the entire tray will disappear

**Comment by benbuck** [comment]
Hi @bitx1,

This sounds like the same issue as #60. Would you mind please reading that one, and letting me know if you agree?

Thanks,
Benbuck

**Comment by bitx1** [comment]
Thanks @benbuck for pointing out the other issue. Yup, it's a duplicate.  #58 details the workaround fix I had to apply... enable "News and Interests" icon again :(. Small nuisance but great if there something that can be done about it. Thanks again.
