### ISSUE TITLE
[feature request] 'restore all' hotkey

### ISSUE THREAD

**Issue by eladkarako** [benbuck/rbtray#63]
RBTray is awesome,  
I am really missing a keyboard combination (from TrayMinimizer),  
that allowed me to restore all of the tray icons in one key-press.  
<sub>I was using <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>R</kbd></sub>  

I guess that an additional entry (of 'restore all') to one of the icon's tray-menu would be equally useful (and would not be requiring any keyboard or mouse hooking either..)  

Not sure what the policy on suggesting new features,  
but I thought I would just leave that here in hope it might be a decent idea :]

**Comment by benbuck** [comment]
Hi @eladkarako,

I think this is a good feature. A while back @dreamforceinc made a change that implements this, hopefully we can figure out how to get that merged soon.

Thanks,
Benbuck

**Comment by eladkarako** [comment]
I'm closing this since I've got a working workaround (quit and reload).
