### ISSUE TITLE
Any chance to add a configuration option to send some programs to tray by default?

### ISSUE THREAD

**Issue by sirtet** [benbuck/rbtray#67]
I have seen that a _similar_ request was declined in Issue #19, but i dare to ask again because i think i have a better explanation of it's use case:

So, i run a number of messaging apps, eg. Signal. And i wish they would all minimize to the tray, like Skype does (well, almost: Skype minimizes to the taskbar too, but keeps running in the tray after u close the window).
Skype's behaviour is probably not that easy to achieve, but minimize to Tray is the next best thing i know so far.

I feel my user experience would be better if i could configure certain apps to always minimize to tray, without the need to remember any of the special actions.

(Hmm, maybe not, because after boot and autostart, they would have to be minimized manually, right? Unless there's another tool to start apps to the tray.)

I understand if you reject again because u want to keep the tool as simple as possible.

**Comment by benbuck** [comment]
Hi @sirtet,

This sounds very similar to issue #44, so I'm going to close it as a duplicate. If you think it's substantially different please let me know.

Thanks,
Benbuck
