### ISSUE TITLE
Feature request: Autostart a program minimized to tray

### ISSUE THREAD

**Issue by DG2YCB** [benbuck/rbtray#68]
Hi, is it possible to implement a feature which allows autostarting a program minimized to tray? This would be a great feature?
Or can I do this already by some commands?
Regards

**Comment by yazan1107** [comment]
Yes this would be wonderful!

**Comment by l0oo** [comment]
From Readme:

If you want it to automatically start after you reboot, create a shortcut to RBTray.exe in your Start menu's Startup group.

On Windows 10 that is located at "C:\Users\YOUR_USERNAME_HERE\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"

But a much quicker way to access it is to press "WIN + R" then type (or copy & paste) shell:Startup

**Comment by rp1231** [comment]
One more vote for this idea

**Comment by dreamforceinc** [comment]
> allows autostarting a program minimized to tray?

Do you mean RBTray or any other program?

**Comment by DG2YCB** [comment]
> > allows autostarting a program minimized to tray?
> 
> Do you mean RBTray or any other program?

I mean another program. I would like my program "rtltcp.exe" to start atutomatically but also to let it automatically be minimized to tray. (Like WhatsAppTray if you know this program. Or like KDocker on Linux.)
Autostaring RBTray itself is easy. Just put it into "Autostart" folder. But currently I cannot let RBTray automatocally start an application and minimize it to tray.

**Comment by Corsage** [comment]
It would be cool if it could take a command-line parameters to the path of the program it should auto-start in minimized to tray.

**Comment by DovieW** [comment]
Any news on this or an alternative way of accomplishing this?

**Comment by benbuck** [comment]
Hi @DG2YCB,

This sounds very similar to the request in issue #20. There are some suggestions there on how to accomplish this. Also, pull requests to implement this are welcome.

Thanks,
Benbuck
