### ISSUE TITLE
right click on minimize button is not working!

### ISSUE THREAD

**Issue by yazan1107** [benbuck/rbtray#69]
right click on minimize button is not working!
i have windows eleven, hotkey is working
i am using lastest version of windows and 4.1.3 rbtray

**Comment by seoMattH** [comment]
I'm having the same issue

**Comment by benbuck** [comment]
Hi @yazan1107 and @seoMattH ,

Do any of the other minimize methods work? If so, please use those instead, not all methods will work for all applications. This is the reason for having multiple methods. If none of the methods work please let me know.

Thanks,
Benbuck
