### ISSUE TITLE
Not Working with IL-Minihost

### ISSUE THREAD

**Issue by nesqulck** [benbuck/rbtray#7]
Hey,
i would really appreciate if i could minimize this programm: 
https://www.image-line.com/support/flstudio_online_manual/html/plugins/Minihost%20Modular.htm

Maybe u have the time to look into that. I've tried using Shift + Mouse aswell but without any success.
This programm is free to download, all u have to do is to register for the forums, so its easier to look into that. 

I have the latest Version of RBTray (64bit 4.6) and the latest Version of Win10

Best Regards

**Comment by benbuck** [comment]
Hi @nesqulck,

I don't have any way to test that program, but I'm wondering if you tried Shift+RightMouse clicking on the title bar instead of on the minimize button? Sorry if you did, it's not clear to me from your message.

-Ben

**Comment by nesqulck** [comment]
Hey Ben,
Its allright. I‘ve found a similliar program which can be minimized to tray on its own. So i switched to this. And yes i tried that. I think the problem is that it minimized to taskbar itself with right click. So RBTray cant hook in that.

**Comment by nesqulck** [comment]
Hey Ben,
it is indeed working as u suggested. Nice work!
