### ISSUE TITLE
Fork is removing copyright notice

### ISSUE THREAD

**Issue by tylerszabo** [benbuck/rbtray#8]
I notice that someone forked this and [quite blatantly](https://github.com/LiuChangFreeman/rbtray/commit/ee1f2cc21168c72f44a16caf437e3302c594e31b#diff-b8de6710c8cd904eaf3c33bc6a8b2206R90) replaced the GPL/Copyright notice.

I reported it to GitHub but they replied as follows:

> Thanks for taking the time to write in about this.
> 
> If you are the copyright holder and want to have the content removed, please file a DMCA takedown with us. Instructions, examples, and policy details are available here:
> 
> https://help.github.com/articles/dmca-takedown-policy
> 
> If you are not the copyright holder, please contact the owner about this matter and have them file a DMCA takedown with us.

**Comment by benbuck** [comment]
Hi Tyler,

Thanks for reporting this. It looks like the removal was non-malicious, it was done for technical reasons. I suggested a better fix to @LiuChangFreeman that would work around this limitation and allow my name to be restored. Hopefully that will resolve it, so I'll close this for now.

Thanks,
Ben
