### ISSUE TITLE
WhatsApp Windows app right click on minimize button does not work

### ISSUE THREAD

**Issue by CrazyEyesDave** [benbuck/rbtray#83]
1. Install WhatsApp windows app from https://www.whatsapp.com/download
- Note: I used the "download for windows" version, not the "get from microsoft" version
2. launch RBTray v4.14
3. Launch WhatsApp application and authenticate
4. Right click on minimize button
5. Nothing happens.

Note that the other shortcuts work fine, but they are not so convenient to use.
(shift + right click on title bar and ctrl+alt+down)

**Comment by OndrejPetrzilka** [comment]
Encountered the same issue.
I have a suspicion that this is caused by customized WhatsApp title bar and it's buttons.

It might be impossible to fix this with general solution and I'm not sure if we want to add specialized solutions for each app that has customized title bar.

**Comment by benbuck** [comment]
Hi @CrazyEyesDave,

Please continue to use whichever methods work, not all methods will work for all applications. This is the reason for having multiple methods.

Thanks,
Benbuck
