### ISSUE TITLE
[question] rbtray persistent own tray icon and menu

### ISSUE THREAD

**Issue by eladkarako** [benbuck/rbtray#88]
not sure if I've misread it or not,  
should rbtray be shown as well in the tray,  
and should it have a right click menu?

if so I'm not getting it,  
not the menu nor the icon.  

I do get the normal functionality though. 

<hr/>

I'm simulating the restore all functionality using this autohotkey script:  

```autohotkey
^+r::  
Run,  D:\Software\rbtray\RBTray.exe --exit
Sleep, 500
Sleep, 500
Sleep, 500
Run,  D:\Software\rbtray\RBTray.exe
return ;
```

**Comment by ivan** [comment]
RBTray doesn't create a tray icon for itself; it does make one tray icon per window that you've sent to the tray.

**Comment by eladkarako** [comment]
yeah I've figured this much,  
got mislead by title of one of the commits.. sorry.  

(it would be a consistent way of telling rbtray is loaded,  
as well as a reliable place for a pop-up menu holding  
exit, restore all, etc..)
