### ISSUE TITLE
Don't allow me to hide my Desktop or Taskbar using new shortcut

### ISSUE THREAD

**Issue by WELZ-gh** [benbuck/rbtray#9]
I can (accidentally) hide to tray my dektop with the new realease (WIn+Alt+Down) which can become annoying.

I accidentally hid my taskbar (hence, my "tray") and the only way for me to get it back was to end the task "explorer" and restart it.

Can you make that new shortcut **not** work on Desktop/Taskbar.

(Windows 10)

**Comment by benbuck** [comment]
I just created version 4.8 which should fix this (it checks to make sure the window had a minimize box when using the hotkey).
